language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
  - master
  - develop

env:
  global:
      - PGPORT=5432
- GO111MODULE=on


services:
- mysql
- redis-server
- postgresql

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
  hosts:
  - local


before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
- cat /etc/hosts

before_script:
- find . -name "*.go" | xargs gofmt -w
- git diff --exit-code
- psql -c 'create database travis_ci_test;' -U postgres

script:
- cd g
- GOARCH=386 go test -v ./...
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)



