language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
  - master
  - develop
  - staging

env:
- GO111MODULE=on
- REDIS_VERSION="4.0.14"

services:
- mysql
- redis-server
- postgresql

addons:
  postgresql: "9.4"
  hosts:
  - local

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
rvm:
  - 2.2



install:
- cat /etc/hosts
- wget http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz
- tar xf redis-$REDIS_VERSION.tar.gz
- (cd redis-$REDIS_VERSION && make)
- ruby --version
- gem install redis -v 3.3.3
- export PATH=./redis-redis-$REDIS_VERSION/src:$PATH
- make start

before_script:
- find . -name "*.go" | xargs gofmt -w
- git diff --name-only --exit-code || exit 1
- psql -c 'create database travis_ci_test;' -U postgres

script:
- GOARCH=386 go test -v ./... || exit 1
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)



