language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
  - master
  - develop
  - staging

env:
- GO111MODULE=on

services:
- mysql
- redis-server
- postgresql

addons:
  postgresql: "9.4"
  hosts:
  - local

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
- cat /etc/hosts
- wget http://download.redis.io/releases/redis-4.0.14.tar.gz
  - tar xf redis-4.0.14.tar.gz
  - (cd redis-4.0.14 && make)
  - ruby --version
  - gem install redis -v 3.3.3
  - export PATH=./redis-redis-4.0.14/src:$PATH
  - make start
  - go get -v -t ./...

before_script:
- find . -name "*.go" | xargs gofmt -w
- git diff --name-only --exit-code || exit 1
- psql -c 'create database travis_ci_test;' -U postgres

script:
- GOARCH=386 go test -v ./... || exit 1
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)



