viewpath = "/home/www/templates"

# MySQL数据库配置
[database]
	debug = true
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"


[redis]
    disk  = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,1"